DMTF/Redfish-Service-Conformance-Check

rf_client.py

Fixes in this Pull request:
- In setup, assume spec mandated values if '/redfish' not implemented by service (issue #7)

Reliability fixes

---

rfs_test/TEST_protocol_details.py

Key iterator for dictionary relative_uris was being modified to add a query fragment and then used as the key to extract the value, but the modified key does not exist in the dictionary

Now forming the request URI from the value rather than the key

---

rfs_test/TEST_protocol_details.py

Assertion checks all resources return 401, but root resource is allowed to be accessed without authorisation, so allow that to be an acceptable response

Allowing root URI to have a status of 200 (OK)

---

rfs_test/TEST_protocol_details.py

httplib returns all headers with lower case keys in the dictionary

Changed key used to check link header from 'Link' to 'link'

---

rfs_test/TEST_protocol_details.py

Depending on the system the json payload may decode as a unicode string. Both the unicode and str classes derive from basestring so this caters for both

Changed isinstance() to check for basestring instead of str

---

rfs_test/TEST_datamodel_schema.py

According to section 6.5.4.4 of the Redfish spec, services should add @odata.etag property to resources
According to section 6.5.5.4 of the Redfish spec, services that support paged collections should add an @odata.nextLink annotation to the Members property if the collection contains a subset of all members

Allow @odata.etag and @odata.nextLink as 'additionalProperties'

---

README.md
rfs_test/__init__.py

To make development and test of a particular assertion more efficient, added an option to run a single assertion instead of the entire suite of assertions.
Snippet of a config that uses this new option (note new **"SingleAssertion"** entry):
```
"RedfishServiceCheckTool_SUTConfiguration": {
"SUTs": [
{
"Password": "********",
"LoginName": "admin",
"AllowAction_LogServiceClearLog": "yes",
"DnsName": "127.0.0.1",
"DisplayName": "my-test-server",
"RedfishVersion": "v1",
"SingleAssertion": "Assertion_6_5_18"
}
],
```

Add option to run a single assertion

---

rfs_test/TEST_protocol_details.py

Previously, this was looping all keys and checking for equality to the nextlink key. Since all keys were being looped, the comparison would fail on any other key and the assertion would be marked as failed
Now explicitly checking for the key in the dictionary

Corrected logic when looking for the @odata.nextLink property

---

rf_sut.py

Assertion_7_2_1 uses the metadata_document_structure from the sut which is populated with a call to parse_metadata_document(), but if a service validates the 'Accept' header then metadata_document_structure will be set to 'None'

Now using XML type in 'Accept' header in parse_metadata_document()

---

rfs_test/TEST_protocol_details.py

Correctly checking MessageId property (instead of looking for the message ID in the error object)
Using prop instead of prop.Name to validate that the patch operation was unsuccessful

Further fixes for validation of patches against read-only fields

---

rfs_test/TEST_protocol_details.py

If the service correctly validates the Accept header, the first resource retrieval would have worked fine, but all subsequent retrievals would have tried to use an xml accept header for a json resource
Note this is the same fix as was applied in commit 928f0e8, but applied to a different assertion

Fix accept header usage for assertion_6_5_20

---

rfs_test/TEST_protocol_details.py

Address incompatibility between Python 2 and 3 with regard to string base type comparison.
Addresses issue #29 that was raised by @jbobzin-insyde

Made string type comparison compatible with Python 2 and 3

---

rfs_test/TEST_protocol_details.py

In assertions 6.5.8 and 6.5.9, added checks to:
- be sure we get an OK (200) status from the GET for the XML schema docs
- catch exceptions when parsing the XML
Also improved the failure logging in 6.5.8 to properly show which schema files it did not find.
Fixes #35

Better error handling for assertions 6.5.8 and 6.5.9

---

rf_sut.py
rf_utility.py
rfs_test/TEST_protocol_details.py
schema.py

Changes include:
- In assertion 6.5.20 added status checking and exception handling
- In assertion 6.5.20 added code to handle fetching XML schemas via relative URIs as well as full URLs
- Removed checks for JSON response payloads when fetching XML schema; the correct fix was to check the status code from the GET
- Strip potential trailing NUL byte at end of XML payloads before parsing
Fixes #21

Improve error handling for assertion 6.5.20

---

rfs_test/TEST_protocol_details.py

In assertions 6.5.8 and 6.5.9, added a check that json_payload is actually JSON (a python dict). If it is not, that likely means that the response from the service did not include the expected Content-Type header with a value including "application/json".
I added a log message that displays the received headers to help with diagnosis.
Fixes #38

Add checks in assertions 6.5.8 and 6.5.9 that response is a dict (JSON)

---

rfs_test/TEST_protocol_details.py

In Assertion_6_5_3(), added additional check to allow `rel="describedby"` in link header (in addition to `rel=describedby`).
If SPMF team agrees that `rel="describedby"` should be allowed, we can merge it.
Fixes #43

assertion 6.5.3: allow rel="describedby" link header

---

rf_sut.py
rfs_test/TEST_protocol_details.py

Updated logic in Assertion_6_4_21() to only warn if the If-None-Match header behavior is not supported by the service (that requirement is a SHOULD rather than a SHALL). 
Fixes #49

Assertion_6_4_21: only warn if If-None-Match header not supported

---

rfs_test/TEST_protocol_details.py

Per discussions in the Tools TF meeting, prefer to use the SessionService rather than the AccountService for testing things like create and delete. This will also address issue #59.
Fixes #59

Change Assertion_6_1_8_4 to create/delete a Session rather than Account

---

rf_sut.py
rfs_test/TEST_protocol_details.py

In Assertion_6_5_40(), made these fixes:
- hardened the checking of the error response
- fixed the logic/handling of the overall assertion_status return value (PASS/WARN/FAIL)
Also made a minor correction to a couple of messages in rf_sut.py (changed "comply" to "conform").
Fixes #68

Harden error response checking in Assertion_6_5_40

---

rfs_test/TEST_protocol_details.py

Assertion_6_5_23_1 had a few problems:
- It did not correctly count the members in the Collections.
- If the Members@odata.count property and the number of Members present were equal, an error was generated that the Members@odata.nextLink must be present. 
- There was no check for the case where the Members@odata.nextLink must not be present.
- Overall assertion_status handling was bad. An overall WARN status could be reported even if there had been FAILs.
This PR fixes those issues.
Fixes #81
Fixes #90

6_5_23_1: fixed Members@odata count and nextLink testing logic

---

rfs_test/TEST_protocol_details.py

Updated Assertion_6_4_18() to make HEAD optional. It was previously generating an error if the HEAD method was not allowed/supported.
Fixes #87

6_4_18: services are not required to support HEAD

---

rfs_test/TEST_protocol_details.py

The type checking for most of the primitive types was incorrect. I hadn't seen this before because there was a counter that limited the checking to the first 40 schema references found in the service. And this was not thorough enough to check a good set of the types.
Made these updates:
- changed the counter to check up to the first 40 schema references _for each resource_ in the service
- fixed the type checking logic
- removed unnecessary python dict to JSON string to python dict conversions
- simplified the debug logging
Fixes #101

6_5_20: corrected primitive type checking

---

rfs_test/TEST_protocol_details.py

For Assertion_6_1_8_1_2(), added type checking of the response body from the POST request to avoid unexpected runtime exception if the body isn't JSON.
Fixes #108

6.1.8.1.2: added type checking to avoid unexpected runtime exception

---

rfs_test/TEST_protocol_details.py

The original code was checking for all namespaces found in Redfish schemas. Corrected the logic to only check for namespaces referenced by the service.
Fixes #78

6_5_8: check namespaces referenced by service are in metadata doc

---

rfs_test/TEST_protocol_details.py

Made the following updates:
- allow Oem property inside Actions
- corrected handling of overall assertion status
- corrected checking of Action names against the schema (check against all Action elements, not just the first one)
- some error message cleanup
Fixes #110

Assertion_6_5_26: allow Oem actions plus additional fixes

---

rfs_test/TEST_protocol_details.py

The assertion is using cached responses, so the second loop that is doing the negative test is just getting cached responses from the calls with the 4.0 OData header. The code is updated to not use cached GETs in this assertion.
Fixes #155

Disable cached responses in assertion 6.4.2.3

---

rfs_test/TEST_protocol_details.py

Updated code for assertion 6.5.3 to not fail if HEAD is not supported.
Fixes #156

Do not fail assertion 6.5.3 if HEAD not supported

---

logger.py

The `row_offset` param in iter_rows() is no longer present in the latest openpyxl package (2.6.0).
But using `min_row=1` instead of `row_offset=1` also works. And `min_row` is available in the latest openpyxl (2.6.0) as well as versions at least back to May 2017 (version 2.4.8).
I also noticed that errors during the opening or saving of the XLSX file were silently ignored. So I added print statements to show any errors during those operations.
Fixes #161

Fix param to iter_rows() to work with recent openpyxl

---

rf_sut.py

See the description of the issue in #165.
Updated `collect_relative_uris()` to remove the persistent caching of resource URIs.
Fixes #165

Remove persistent caching of resource URIs

---

rf_utility.py

As described in issue #167, http__modify_resource() does not correctly handle the case of an empty body (like for DELETE requests). Made small update to check for the existence of body payload before trying to convert it to JSON.
Fixes #167

Update http__modify_resource() to handle empty body

---

README.md

This the short-term fix for issue 176 - just documenting the spec version that matches the assertion names shown in the reports. A subsequent PR will address the renaming of the assertions.

Add Redfish spec version for assertion names to README

---

rfs_test/TEST_protocol_details.py

Assertion_6_5_6_5() was doing a GET on the dictionary key instead of the value in the dict.
Fixes #179

Fix assertion 6.5.6.5 to get the target URI correctly

---

rf_utility.py

Updates:
- In `Connect_Server_NoSSL()`, there is a check that should be for Python3 versions less than 3.4.3. But it was checking for less than or equal to 3.4.3.
- Also changed the version tests to be more pythonic. For example:
old:
`if (sys.version_info.major == 3 and sys.version_info.minor == 4 and sys.version_info.micro < 3)`
new:
`if sys.version_info[0:3] < (3, 4, 3):`
- Cleaned up dead/redundant code in `Connect_Server_NoSSL_NoHTTPS()`.
- Cleaned up some unused/uninitialized variables.
Fixes #180 
Thanks to @LeeTroy for finding this.

Fix test for python3 version less than 3.4.3

---

rfs_test/__init__.py

Per discussion in the Tools TF call, disabled the entire TEST_datamodel_schema.py module.
These assertions (7.*) just validate the CSDL schema files or validate that the service payloads adhere to the schemas. These tests are already covered by the Redfish-Service-Validator, tools in https://github.com/DMTF/Redfish-Tools, and Travis CI tests in https://github.com/DMTF/Redfish.
Fixes #181

Disable out-of-scope datamodel schema tests

---

rfs_test/TEST_protocol_details.py

I fixed the KeyError seen in issue #186.
But note the following oddities here:
1. Testing for required properties in the JSON response payloads is handled by the Redfish-Service-Validator. The Redfish-Service-Conformance-Check tool should not even be doing this type of check (should be resolved when issue #177 is fixed).
2. Assertion_6_5_14 is supposed to be checking the format of the "@odata.context" value but is instead checking for missing required properties.
Fixes #186

Fix KeyError in Assertion_6_5_14

---

logger.py
rfs_test/TEST_protocol_details.py

The `Server` response header is no longer required as of the 1.9.0 spec. Removed it from the list of required headers being checked.
Also, while testing this in a newly installed Python environment I encountered an unrelated problem that `Workbook.get_active_sheet()` was no longer present in the latest version of `openpyxl`. Apparently that method was deprecated about 5 years ago (in version 2.3) and has been removed from the latest versions (3.0.n). So I went ahead and updated the code in this PR to use the supported `Workbook.active` property.
Fixes #188

Remove "Server" as required response header; fix deprecated openpyxl call

---

rfs_test/TEST_protocol_details.py

I also corrected a problem where the overall status of this assertion was not reported correctly (it could report an overall status of WARN or PASS even if one or more URIs got a FAIL result).
Fixes #191

Skip Sensors, Thermal and Power URIs for assertion 6.4.25
